dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t xmorepo:$TRAVIS_BUILD_NUMBER .
      - docker images
      - docker tag xmorepo:$TRAVIS_BUILD_NUMBER $DOCKER_USERNAME/xmorepo:$TRAVIS_BUILD_NUMBER
      - docker push $DOCKER_USERNAME/xmorepo:$TRAVIS_BUILD_NUMBER
      - docker tag $DOCKER_USERNAME/xmorepo:$TRAVIS_BUILD_NUMBER $DOCKER_USERNAME/xmorepo
      - docker push $DOCKER_USERNAME/xmorepo:latest
    - stage: test
      script: echo "running test 1"
    - script: echo "running test 2"